### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by nickpalladino** [travisgoodspeed/goodtag#2]
Hey @travisgoodspeed, I had a few goodtag11 boards made up to evaluate the RF430FRL152H. I also forked GoodV and updated it a bit. Would you have an issue with me putting up my extra boards for sale and publishing GoodV in the Play Store? I didn't see any license information in the repos.

Thanks,
Nick

**Comment by travisgoodspeed** [comment]
Forks are welcome, of course.  Please label it as a fork if you've made changes and kindly share a devkit with a student when you get a chance.
